### ISSUE TITLE
Rebuild docker image once all issues fixed

### ISSUE THREAD

**Issue by OscartGiles** [alan-turing-institute/DetectorCheckerWebApp#18]
There are a number of changes to the DetectorChecker code required:: https://github.com/alan-turing-institute/DetectorChecker/issues (see issue 49 and 50).

Need to rebuild the docker file once these are merged.

**Comment by tomaslaz** [comment]
This has been fixed with `RUN apt-get update; apt-get install -y libhdf5-dev` and `RUN Rscript -e "install.packages('hdf5r')"` in the dockerfile.
